Update version on a branch only if that branch exists.

diff --git a/.github/actions/update-chart/action.yaml b/.github/actions/update-chart/action.yaml
--- a/.github/actions/update-chart/action.yaml
+++ b/.github/actions/update-chart/action.yaml
@@ -18,25 +18,33 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Validate branch existence
+      if: inputs.branch == 'upstream/b-open'
+      shell: bash
+      run: |
+        echo "Validating specific branch: ${{ inputs.branch }}"
+        
+        # Check if the branch input is empty
+        if [ -z "${{ inputs.branch }}" ]; then
+          echo "::error::Branch input is empty. Blocking pipeline."
+          exit 1
+        fi
+
+        # Check if the branch exists on the remote
+        CHECK=$(git ls-remote --heads https://x-access-token:${{ inputs.github-pat }}@github.com/${{ inputs.chart-repo }}.git ${{ inputs.branch }})
+        
+        if [ -z "$CHECK" ]; then
+          echo "::error::Branch '${{ inputs.branch }}' does not exist in ${{ inputs.chart-repo }}!"
+          exit 1
+        fi
+        echo "Branch '${{ inputs.branch }}' verified."
+
     - name: Checkout chart repo
       uses: actions/checkout@v4
       with:
         repository: ${{ inputs.chart-repo }}
         token: ${{ inputs.github-pat }}
         ref: ${{ inputs.branch }}
-
-    # - name: Check for existing branch
-    #   id: check_branch
-    #   shell: bash
-    #   run: |
-    #     git fetch origin
-    #     if git show-ref --verify --quiet refs/heads/automatic_update; then
-    #       echo "Branch exists"
-    #       git checkout automatic_update
-    #     else
-    #       echo "Branch does not exist"
-    #       git checkout -b automatic_update
-    #     fi
 
     - name: Update appVersion
       shell: bash
